# Generated by Django 4.2.23 on 2025-07-03 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_course_lesson_progress_liveclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveclass',
            name='scheduled_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
