# Generated by Django 4.2.23 on 2025-07-03 03:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_liveclass_scheduled_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveclass',
            name='scheduled_datetime',
            field=models.DateField(default=1),
            preserve_default=False,
        ),
    ]
