# Generated by Django 4.2.23 on 2025-07-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_liveclass_scheduled_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='liveclass',
            name='scheduled_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
